# Generated by Django 6.0.5 on 2026-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_movie_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
