# Generated by Django 6.0.5 on 2026-05-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_movie_trailer_url_movie_trailer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_id',
        ),
    ]
