# Generated by Django 6.0.5 on 2026-05-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_review_name_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(help_text="Direct link to actor's square photo")),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_photos',
            field=models.TextField(blank=True, help_text='Paste Image URLs separated by commas'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube Embed link'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='movies', to='reviews.actor'),
        ),
    ]
